import { randomUUID } from "node:crypto";
import fs from "node:fs";
import path from "node:path";
import {
  alternatives,
  associations,
  productAlternativeMap,
  products,
} from "../src/data/seed";

// Generates supabase/seed.sql from src/data/seed.ts, mapping the
// human-readable local ids to real UUIDs for the products/alternatives
// primary keys defined in supabase/migrations/0001_init.sql.

function sqlString(value: string): string {
  return `'${value.replace(/'/g, "''")}'`;
}

function sqlArray(values: string[]): string {
  if (values.length === 0) return "'{}'";
  return `ARRAY[${values.map(sqlString).join(", ")}]`;
}

function sqlNullable(value: string | null | undefined): string {
  return value == null ? "NULL" : sqlString(value);
}

const productIdMap = new Map(products.map((p) => [p.id, randomUUID()]));
const alternativeIdMap = new Map(alternatives.map((a) => [a.id, randomUUID()]));

const lines: string[] = [
  "-- Generated by scripts/generate-seed-sql.ts — do not edit by hand.",
  "-- Run supabase/migrations/0001_init.sql first, then run this file.",
  "",
  "insert into products (id, slug, name, brand, category, image_url) values",
];

lines.push(
  products
    .map((p, i) => {
      const id = productIdMap.get(p.id)!;
      const row = `  (${sqlString(id)}, ${sqlString(p.slug)}, ${sqlString(p.name)}, ${sqlString(p.brand)}, ${sqlString(p.category)}, ${sqlString(p.imageUrl)})`;
      return row + (i === products.length - 1 ? ";" : ",");
    })
    .join("\n"),
);

lines.push("", "insert into alternatives (id, slug, name, brand, basis_text, basis_confidence, basis_sources, affiliate_url, affiliate_type, category, image_url) values");
lines.push(
  alternatives
    .map((a, i) => {
      const id = alternativeIdMap.get(a.id)!;
      const row = `  (${sqlString(id)}, ${sqlString(a.slug)}, ${sqlString(a.name)}, ${sqlString(a.brand)}, ${sqlString(a.basisText)}, ${a.basisConfidence}, ${sqlArray(a.basisSources)}, ${sqlNullable(a.affiliateUrl)}, ${sqlNullable(a.affiliateType)}, ${sqlString(a.category)}, ${sqlString(a.imageUrl)})`;
      return row + (i === alternatives.length - 1 ? ";" : ",");
    })
    .join("\n"),
);

lines.push("", "insert into associations (product_id, claim_text, source_urls, confidence_tier, theme_tag, date_checked) values");
lines.push(
  associations
    .map((assoc, i) => {
      const productId = productIdMap.get(assoc.productId);
      if (!productId) {
        throw new Error(`No product found for association ${assoc.id} (productId ${assoc.productId})`);
      }
      const row = `  (${sqlString(productId)}, ${sqlString(assoc.claimText)}, ${sqlArray(assoc.sourceUrls)}, ${assoc.confidenceTier}, ${sqlNullable(assoc.themeTag)}, ${sqlString(assoc.dateChecked)})`;
      return row + (i === associations.length - 1 ? ";" : ",");
    })
    .join("\n"),
);

lines.push("", "insert into product_alternative_map (product_id, alternative_id, rank) values");
lines.push(
  productAlternativeMap
    .map((m, i) => {
      const productId = productIdMap.get(m.productId);
      const alternativeId = alternativeIdMap.get(m.alternativeId);
      if (!productId) throw new Error(`No product found for map entry productId ${m.productId}`);
      if (!alternativeId) throw new Error(`No alternative found for map entry alternativeId ${m.alternativeId}`);
      const row = `  (${sqlString(productId)}, ${sqlString(alternativeId)}, ${sqlString(m.rank)})`;
      return row + (i === productAlternativeMap.length - 1 ? ";" : ",");
    })
    .join("\n"),
);

const outPath = path.join(__dirname, "..", "supabase", "seed.sql");
fs.writeFileSync(outPath, lines.join("\n") + "\n");
console.log(`Wrote ${outPath}`);
console.log(`  ${products.length} products, ${alternatives.length} alternatives, ${associations.length} associations, ${productAlternativeMap.length} map entries`);
